/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package tasktimer

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class TaskTimerPlugin implements Plugin<Project> {
    void apply(Project project) {

        project.getGradle().addListener(new TimingsListener())

    }
}
